const skills = [
  { id: 0, label: 'Communication' },
  { id: 1, label: 'Teamwork' },
  { id: 2, label: 'Problem-solving' },
  { id: 3, label: 'Time management' },
  { id: 4, label: 'Leadership' },
  { id: 5, label: 'Adaptability' },
  { id: 6, label: 'Creativity' },
  { id: 7, label: 'Work ethic' },
  { id: 8, label: 'Interpersonal skills' },
  { id: 9, label: 'Attention to detail' },
  { id: 10, label: 'Critical thinking' },
  { id: 11, label: 'Decision-making' },
  { id: 12, label: 'Organizational skills' },
  { id: 13, label: 'Stress management' },
  { id: 14, label: 'Project management' },
  { id: 15, label: 'Negotiation' },
  { id: 16, label: 'Conflict resolution' },
  { id: 17, label: 'Emotional intelligence' },
  { id: 18, label: 'Active listening' },
  { id: 19, label: 'Customer service' },
  { id: 20, label: 'Networking' },
  { id: 21, label: 'Public speaking' },
  { id: 22, label: 'Writing' },
  { id: 23, label: 'Presentation skills' },
  { id: 24, label: 'Analytical skills' },
  { id: 25, label: 'Technical skills' },
  { id: 26, label: 'Research skills' },
  { id: 27, label: 'Sales skills' },
  { id: 28, label: 'Marketing skills' },
  { id: 29, label: 'Financial management' },
  { id: 30, label: 'Budgeting' },
  { id: 31, label: 'Strategic planning' },
  { id: 32, label: 'Mentoring' },
  { id: 33, label: 'Teaching' },
  { id: 34, label: 'Coaching' },
  { id: 35, label: 'Training' },
  { id: 36, label: 'Data analysis' },
  { id: 37, label: 'Computer literacy' },
  { id: 38, label: 'Programming' },
  { id: 39, label: 'Multitasking' },
  { id: 40, label: 'Delegation' },
  { id: 41, label: 'Supervisory skills' },
  { id: 42, label: 'Report writing' },
  { id: 43, label: 'Editing' },
  { id: 44, label: 'Social media management' },
  { id: 45, label: 'SEO' },
  { id: 46, label: 'Content creation' },
  { id: 47, label: 'Event planning' },
  { id: 48, label: 'Volunteer management' },
  { id: 49, label: 'Fundraising' },
];

const cuisines = [
  { id: 0, label: 'Italian' },
  { id: 1, label: 'Chinese' },
  { id: 2, label: 'Mexican' },
  { id: 3, label: 'Indian' },
  { id: 4, label: 'French' },
  { id: 5, label: 'Japanese' },
  { id: 6, label: 'Thai' },
  { id: 7, label: 'Greek' },
  { id: 8, label: 'Spanish' },
  { id: 9, label: 'Korean' },
  { id: 10, label: 'Vietnamese' },
  { id: 11, label: 'Turkish' },
  { id: 12, label: 'Moroccan' },
  { id: 13, label: 'Lebanese' },
  { id: 14, label: 'Ethiopian' },
  { id: 15, label: 'Brazilian' },
  { id: 16, label: 'Argentinian' },
  { id: 17, label: 'Caribbean' },
  { id: 18, label: 'Peruvian' },
  { id: 19, label: 'Russian' },
];

export { skills, cuisines };
